{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "myproject.fullname" . }}-networkpolicy
  namespace: frontend-ns
spec:
  podSelector: {} # Applique cette règle à tous les pods de frontend-ns
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: frontend-ns # Autorise uniquement le trafic interne à frontend-ns
  policyTypes:
    - Ingress
{{- end }}