apiVersion: v1
kind: Service
metadata:
  name: {{ include "myproject.fullname" . }}-frontend-service
  namespace: frontend-ns
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  type: LoadBalancer