apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myproject.fullname" . }}-backend
  namespace: backend-ns
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          livenessProbe:                     # Vérifie que le backend est vivant
            httpGet:
              path: /health                     # Endpoint de santé
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 5           # Délai avant le premier check
            periodSeconds: 10                # Fréquence des checks
          readinessProbe:                    # Vérifie que le backend est prêt à recevoir du trafic
            httpGet:
              path: /health                     # Endpoint de santé
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 5           # Délai avant le premier check
            periodSeconds: 10                # Fréquence des checks