apiVersion: v1
kind: Service
metadata:
  name: {{ include "myproject.fullname" . }}-backend-service
  namespace: backend-ns
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: LoadBalancer