name: Destroy Workflow


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - prod



jobs:
  terraform-destroy:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: self-hosted
    
    environment: ${{ github.event.inputs.environment }}
    
    steps:



      - name: 🔀 Checkout repository
        uses: actions/checkout@v4



      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/161911340849/locations/global/workloadIdentityPools/filrouge-formation/providers/oidc-github-provider'
          service_account: 'filrouge-main-sa@filrouge-452215.iam.gserviceaccount.com'



      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            service-account:filrouge-452215/sa-${{ github.event.inputs.environment }}



      - name: Setup credentials files for Terraform ${{ github.event.inputs.environment }}
        id: credentials
        run: |
          echo "${{ steps.secrets.outputs.service-account }}" | base64 --decode > ./filrouge-${{ github.event.inputs.environment }}-sa.json
          ls -la



      - name: Use terraform
        uses: hashicorp/setup-terraform@v3



      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: terraform



      - name: Terraform workspace ${{ github.event.inputs.environment }}
        id: workspace
        run: terraform workspace select ${{ github.event.inputs.environment }}
        working-directory: terraform



      - name: Terraform Destroy
        id: plan
        run: terraform destroy --auto-approve
        continue-on-error: true
        working-directory: terraform